language: csharp

sudo: required
dist: xenial
install:
  - mozroots --import --sync
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
matrix:
  include:
    - mono: latest
      dotnet: 3.0.100
      os: linux
    - mono: latest
      dotnet: 3.0.100
      os: osx
 
script: 
  - ./fake.sh build target AllCore
  
branches:
  except:
    - gh-pages
    - release
