language: csharp

sudo: false  # use the new container-based Travis infrastructure 

matrix:
  include:
    - mono: latest
      dotnet: 2.1.3
      env: USE_MSBUILD=1
      os: linux

before_install:
  - chmod +x build.sh
 
script: 
  - ./build.sh AllCore
  
branches:
  except:
    - gh-pages
    - release