trigger:
  branches:
    include:
    - master
    exclude:
    - gh-pages
    - release
    
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: ./fake.cmd build
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: |
      export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/
      dotnet tool restore
      ./fake.sh build
