trigger:
  branches:
    include:
    - master
    exclude:
    - gh-pages
    - release
    
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: ./fake.cmd build
- job: macOS
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - bash: |
      export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.1-api/
      ./fake.sh build
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - bash: |
      export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.7.1-api/
      ./fake.sh build
