trigger:
  branches:
    exclude:
    - gh-pages
    - release
    
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: ./fake.cmd build
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: . '$(Build.SourcesDirectory)/fake.sh' build
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: . '$(Build.SourcesDirectory)/fake.sh' build
